=== axelajv/ProjetR-D/SVEDI_Xedix/Base de données/baseTest.dtd
<!-- DTD svedi ... -->
<!-- (C) ... Mon Oct 27 14:01:24 2014 -->
<!ELEMENT svedi (filiere)* >
<!-- filiere=3 -->
<!ELEMENT ID (#PCDATA) >
<!-- #PCDATA=1 -->
<!ELEMENT filiere (ID|ID_Utilisateur|Nom)* >
<!-- ID=3 | ID_Utilisateur=3 | Nom=3 -->
<!ELEMENT ID_Utilisateur (#PCDATA) >
<!-- #PCDATA=1 -->
<!ELEMENT Nom (#PCDATA) >
<!-- #PCDATA=1 -->

=== axelajv/ProjetR-D/SVEDI_Xedix/Base de données/baseTest.xml
<?xml version="1.0"?>
<!DOCTYPE svedi SYSTEM "baseTest.dtd">
<?XEDIX id 1 ?>

<svedi>
        <filiere>
            <ID>"8"</ID>
            <Nom>"MIAGE M2"</Nom>
            <ID_Utilisateur>"42"</ID_Utilisateur>
        </filiere>
        <filiere>
            <ID>"9"</ID>
            <Nom>"MIAGE L3"</Nom>
            <ID_Utilisateur>"36"</ID_Utilisateur>
        </filiere>
        <filiere>
            <ID>"10"</ID>
            <Nom>"test"</Nom>
            <ID_Utilisateur>"36"</ID_Utilisateur>
        </filiere>

</svedi>
